name: Static Analysis
on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - linux-amd64-fmt
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest